# =====================================================
# 1️⃣ Spring Boot Deployment
# =====================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: mahmoudkrichen/mahmoudkrichen4twin2:26
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/studentdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"

---
# =====================================================
# 2️⃣ Spring Boot Service (NodePort)
# =====================================================
apiVersion: v1
kind: Service
metadata:
  name: student-management
  namespace: devops
  spec:
    type: NodePort
    selector:
      app: student-management
    ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30080
